version: '3'
services:
  chatbot:
    image: ketlin/chatbot:latest
    container_name: chatbot
    build:
      context: .
      dockerfile: ./dockers/chatbot/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/software
