# Generated by Django 3.2.11 on 2022-02-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
