# Generated by Django 3.2.11 on 2022-03-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0003_user_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='protocol',
        ),
        migrations.AddField(
            model_name='user',
            name='chatbot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='home.chatbot', verbose_name='Chatbot'),
            preserve_default=False,
        ),
    ]
