# Generated by Django 3.2.11 on 2022-02-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Código já existe.'}, help_text='Código único de identificação da questão.', max_length=50, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=False, help_text='Verifica se a questão está ativo no sistema.', verbose_name='Está ativo?')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual a questão foi feita.', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual a questão foi atualizada.', verbose_name='Atualizado em')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ('created_at',),
            },
        ),
    ]
