# Generated by Django 3.2.11 on 2022-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_relation',
            field=models.CharField(default='', help_text='Código usado para identificar respostas relacionadas', max_length=15, verbose_name='Código relacionado'),
            preserve_default=False,
        ),
    ]
