# Generated by Django 3.2.11 on 2022-02-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20220213_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='body',
            field=models.CharField(default='', help_text='Enunciado da questão', max_length=500, verbose_name='Questão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(help_text='Resposta para essa questão', max_length=500, verbose_name='Resposta'),
        ),
    ]
