# Generated by Django 3.2.11 on 2022-02-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20220213_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('created_at',), 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
