# Generated by Django 3.2.11 on 2022-02-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_code_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='code_relation',
            new_name='input_before',
        ),
    ]
