# Generated by Django 3.2.11 on 2022-02-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_rename_code_relation_question_input_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='input_before',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_inputs', to='questions.question', verbose_name='Pergunta anterior'),
        ),
    ]
