# Generated by Django 3.2.11 on 2022-02-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_question_input_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(help_text='Enunciado da entrada do usuário', max_length=500, verbose_name='Entrada'),
        ),
    ]
