# Generated by Django 3.2.11 on 2022-02-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_question_input_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Verifica se a questão está ativo no sistema.', verbose_name='Está ativo?'),
        ),
    ]
