# Generated by Django 3.2.11 on 2022-03-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('questions', '0015_alter_question_input_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.chatbot', verbose_name='Chatbot'),
            preserve_default=False,
        ),
    ]
