# Generated by Django 3.2.11 on 2022-02-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_capture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='code',
        ),
        migrations.AlterField(
            model_name='capture',
            name='email',
            field=models.EmailField(help_text='Email do usuário capturado.', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text='Captura o sexo de uma pessoa.', max_length=1, verbose_name='Sexo'),
        ),
    ]
