# Generated by Django 3.2.11 on 2022-02-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0003_auto_20220213_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='age',
            field=models.IntegerField(blank=True, default=0, help_text='Idade capturada do usuário.', null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='cep',
            field=models.CharField(blank=True, help_text='Captura do CEP do usuário', max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='document',
            field=models.CharField(blank=True, help_text='Documento capturado do usuário, pode ser CPF ou CNPJ.', max_length=25, verbose_name='CPF/CNPJ'),
        ),
    ]
