# Generated by Django 3.2.11 on 2022-02-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0005_auto_20220213_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='complement',
            field=models.CharField(blank=True, help_text='Complemento do endereço', max_length=100, verbose_name='Complemento'),
        ),
    ]
