# Generated by Django 3.2.11 on 2022-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(error_messages={'unique': 'Protocolo já existe.'}, help_text='Protocolo do chatbot do usuário', max_length=25, unique=True, verbose_name='protocolo')),
                ('is_active', models.BooleanField(default=True, help_text='Verifica se a questão está ativo no sistema.', verbose_name='Está ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data na qual o usuário foi criado.', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data na qual o usuário foi atualizado.', verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbot',
                'db_table': 'chatbot',
                'ordering': ('created_at',),
            },
        ),
    ]
